CREATE TABLE IF NOT EXISTS `purchase_issues` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `order_item_id` bigint unsigned NOT NULL,
  `root_item_id` bigint unsigned NOT NULL,
  `order_id` bigint unsigned NOT NULL,
  `order_retailer_id` bigint unsigned DEFAULT NULL,
  `retailer_id` bigint unsigned DEFAULT NULL,
  `qty` int unsigned NOT NULL DEFAULT 1,
  `issue_type` varchar(50) NOT NULL,
  `severity` varchar(20) NOT NULL DEFAULT 'medium',
  `status` varchar(30) NOT NULL DEFAULT 'open',
  `notes` text DEFAULT NULL,
  `requires_customer_action` tinyint(1) NOT NULL DEFAULT 0,
  `customer_contacted_at` timestamp NULL DEFAULT NULL,
  `customer_replied_at` timestamp NULL DEFAULT NULL,
  `resolution_type` varchar(50) DEFAULT NULL,
  `resolution_notes` text DEFAULT NULL,
  `resolved_at` timestamp NULL DEFAULT NULL,
  `created_by_user_id` bigint unsigned DEFAULT NULL,
  `updated_by_user_id` bigint unsigned DEFAULT NULL,
  `resolved_by_user_id` bigint unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `purchase_issues_order_item_id_foreign` (`order_item_id`),
  KEY `purchase_issues_root_item_id_index` (`root_item_id`),
  KEY `purchase_issues_order_id_status_index` (`order_id`,`status`),
  KEY `purchase_issues_root_item_id_status_index` (`root_item_id`,`status`),
  KEY `purchase_issues_status_severity_index` (`status`,`severity`),
  KEY `purchase_issues_customer_action_index` (`requires_customer_action`,`status`),
  KEY `purchase_issues_order_retailer_id_index` (`order_retailer_id`),
  KEY `purchase_issues_retailer_id_index` (`retailer_id`),
  CONSTRAINT `purchase_issues_order_item_id_foreign` FOREIGN KEY (`order_item_id`) REFERENCES `order_items` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `purchase_issues_order_id_foreign` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `purchase_issues_created_by_user_id_foreign` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `purchase_issues_updated_by_user_id_foreign` FOREIGN KEY (`updated_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `purchase_issues_resolved_by_user_id_foreign` FOREIGN KEY (`resolved_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
